### ISSUE TITLE
The role_name  value cannot be modiefied 

### ISSUE THREAD

**Issue by mtannous** [sperreault/ansible-scaleio#10]
The installation of TB packckage is failing, due to role_name = mdm is not actually being set to mdm, but it was set to tb. It seems that role_name cannot be overwritten, hence need to create a variable to  set it to the appropriate role_name in these following the 
mdm/tasks/main.yml
tb/tasks/main.yml
lia/tasks/main.yml

**Comment by sperreault** [comment]
Thanks for the problem, updated your code to use file_glob_name instead of tmp_role_name.

**Comment by mtannous** [comment]
Awesome, thank you!
