### ISSUE TITLE
MDM facts are not accessible on nodes when installing MDM

### ISSUE THREAD

**Issue by howels** [sperreault/ansible-scaleio#6]
Apologies if I've missed something but when running through an install using Ansible 2.0 I am seeing messages like this:
```
TASK [mdm : install package] ***************************************************
task path: /home/ansible-scaleio/roles/install_scaleio.yml:9
fatal: [scaleio-2]: FAILED! => {"failed": true, "msg": "ERROR! list object has no element 0"}
fatal: [scaleio-3]: FAILED! => {"failed": true, "msg": "ERROR! 'scaleio_mdm_secondary_ip' is undefined"}
```

I can see that the facts have been gathered previously and even tried inserting a null task to ensure that this was the case, but the nodes seem unable to access them. Any hints?

Many thanks

**Comment by sperreault** [comment]
Ok...I was able to reproduce the error on ansible 2.0.0.2 so I'll work on fixing it.
