### ISSUE TITLE
Incorrect CentOS Distribution Name 

### ISSUE THREAD

**Issue by mtannous** [sperreault/ansible-scaleio#9]
1- Need to rename the Centos.yml to CentOS.yml file in os-var: due to this error 
fatal: [node0]: FAILED! => {"changed": false, "failed": true, "file": "/os_vars/CentOS.yml", "msg": "Source file not found."}

fatal: [node0]: FAILED! => {"failed": true, "reason": "the file_name '/root/ansible-scaleio/install_scaleio_CentOS.yml' does not exist, or is not readable"}

2- In roles/install_scaleio_Centos.yml , need  to change the ansible_distribution to: CentOS,  because  it is wasn't actually copying the files and installing the mdm.

**Comment by sperreault** [comment]
Thanks for the fix.
